dist: bionic
sudo: required
language: cpp

env:
    - SETUP_CURSES="sudo apt remove -y libncursesw5-dev"
    - SETUP_CURSES="sudo apt install -y libncursesw5-dev"

compiler:
    - clang
    - gcc

before_install:
    - sudo apt update
    - eval "${SETUP_CURSES}"

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --target demos

notifications:
    email: false
